CoherentLabs/GameUIComponents

components/rangeslider/README.md
components/rangeslider/components-theme.css
components/rangeslider/demo/demo.html
components/rangeslider/demo/demo.js
components/rangeslider/index.js
components/rangeslider/orientationUnitsNames.js
components/rangeslider/package.json
components/rangeslider/script.js
components/rangeslider/styles/horizontal.css
components/rangeslider/styles/vertical.css
components/rangeslider/templates/horizontal.html
components/rangeslider/templates/horizontalTwoHandles.html
components/rangeslider/templates/vertical.html
components/rangeslider/templates/verticalTwoHandles.html
tools/tests/karma.conf.js
tools/tests/rangeslider/test.js
tools/tests/styles/rangeslider.css

https://coherent-labs.atlassian.net/browse/GUI-72
Inside the task there is a description on how the rangeslider should work

Range slider

---

components/dropdown/README.md
components/dropdown/demo/demo.html
components/dropdown/script.js
lib/components.js

Task (with basic test idea): https://coherent-labs.atlassian.net/browse/COH-14869
For the scroll to work in the attached sample in the JIRA task, see the end of the Test Plan section.

Fix/Remember Dropdown State when using data binding

---

components/automatic-grid/README.md
components/automatic-grid/components-theme.css
components/automatic-grid/demo/demo.html
components/automatic-grid/demo/demo.js
components/automatic-grid/index.js
components/automatic-grid/package.json
components/automatic-grid/script.js
components/automatic-grid/style.css
components/automatic-grid/template.html
components/rangeslider/script.js
tools/tests/automatic-grid/test.js
tools/tests/karma.conf.js
tools/tests/styles/automatic-grid.css

JIRA Task: https://coherent-labs.atlassian.net/browse/GUI-82
-----------
The name of the component is the first one that I came up with. If you think of a better one, please do let me know so I can change it.
Also here are some possible todo's that I decided not to do for now. If you think we need them leave a comment so I can add them to this PR.
Possible TODO's: 
- Add a drag enter and drag end events for cells that changes their class, so clients can use it as an effect. 
- Add a spatial navigation in the grid. Decided against it for now as it would take some time to implement.
- Sortable grid. Create helper functions that will allow clients to easily sort the grid items.

Automatic grid

---

README.md

Do you think this is enough as an explanation and visible enough, or in the right place/section?

Document use case with Gameface Data Binding

---

components/automatic-grid/coherent-gameface-components-theme.css
components/checkbox/coherent-gameface-components-theme.css
components/checkbox/style.css
components/dropdown/coherent-gameface-components-theme.css
components/grid/coherent-gameface-components-theme.css
components/menu/coherent-gameface-components-theme.css
components/menu/menus/menu.css
components/modal/coherent-gameface-components-theme.css
components/modal/style.css
components/progress-bar/coherent-gameface-components-theme.css
components/radial-menu/coherent-gameface-components-theme.css
components/rangeslider/coherent-gameface-components-theme.css
components/router/coherent-gameface-components-theme.css
components/scrollable-container/coherent-gameface-components-theme.css
components/slider/coherent-gameface-components-theme.css
components/tabs/coherent-gameface-components-theme.css
components/tabs/style.css
theme/coherent-gameface-components-theme.css

Simply move individual/specific components styles from the theme directly to the components css files and update it in all components folders where necessary.
It would be easier to review the first commit first.

Sanitize Components Theme

---

components/automatic-grid/demo/demo.html
components/automatic-grid/package.json
components/checkbox/package.json
components/checkbox/script.js
components/dropdown/package.json
components/dropdown/script.js
components/menu/menus/menu.js
components/menu/package.json
components/router/demo/demo-browser-history.html
components/router/demo/demo-hash-history.html
components/router/history.js
components/router/package.json
components/router/route.js
components/scrollable-container/package.json
components/scrollable-container/script.js
components/slider/package.json
components/slider/script.js
components/tabs/package.json
components/tabs/script.js

JIRA task: https://coherent-labs.atlassian.net/browse/COH-15294
Note that after a discussion linked in the comments I have decided to remove detaching event listeners altogether except for global ones.

Remove detaching event listeners except for global ones

---

.github/workflows/node.js.yml
README.md
docs/README.md
package.json
tools/tests/README.md

Update the readme of the components, documentation and tests.

Better documentation

---

.github/workflows/publish.yml
package.json
scripts/helpers.js
scripts/publish.js

Created a script to check if a component has an update.
Created a github action to publish on push in master, because merge in not a valid trigger event: https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359

Add action for auto publish

---

components/automatic-grid/package.json
components/checkbox/package.json
components/dropdown/package.json
components/form-control/package.json
components/grid/package.json
components/menu/package.json
components/modal/package.json
components/progress-bar/package.json
components/radial-menu/package.json
components/radio-button/package.json
components/rangeslider/package.json
components/router/package.json
components/scrollable-container/package.json
components/slider/package.json
components/switch/package.json
components/tabs/package.json
components/tooltip/package.json
lib/package.json
samples/user_interface/main/package.json
samples/user_interface/settings/package.json
samples/user_interface/shop/package.json
tools/cli/package.json

These are the new versions - https://docs.google.com/spreadsheets/d/1MgGAY6fw97HaR7_WYI-6cD0_EeEdvoV6KR3IBzeBoss/edit?usp=sharing

Update the components', the library's and the cli's versions

---

components/form-control/README.md
components/form-control/package.json
components/form-control/script.js
tools/tests/actions.js
tools/tests/form-control/test.js
tools/tests/form-control/validation.test.js
tools/tests/form-control/xhr.test.js

Added the xhr that is created on submit as a property of the form.

Expose xhr

---

components/checkbox/package.json
components/checkbox/script.js
components/checkbox/style.css
components/form-control/demo/demo.html
components/radio-button/package.json
components/radio-button/script.js
components/radio-button/style.css
tools/tests/form-control/test.js

Added disabled attributes for the:
* checkbox
* radio group wrapper
* radio button
I made two commits - the first one is about the disabled attribute of the checkbox and the second one is about the disabled attribute for the radio group/button so it would be easier for review.

Checkbox disabled attribute

---

components/checkbox/package.json
components/checkbox/script.js
components/dropdown/README.md
components/dropdown/package.json
components/dropdown/script.js
components/dropdown/style.css
tools/tests/dropdown/multiple-dropdown.test.js
tools/tests/dropdown/test.js
tools/tests/form-control/test.js

There are some "workaround" avoiding the pesky caching feature.

Dropdown disabled atribute and selected attributes on options

---

components/form-control/README.md
components/form-control/demo/demo.html
components/form-control/demo/server.js
components/form-control/script.js
scripts/forms-server.js
tools/tests/form-control/validation.test.js

Task: [Here](https://coherent-labs.atlassian.net/browse/COH-15431)

Custom forms validation

---

components/form-control/README.md
components/form-control/errorMessages.js
components/form-control/package.json
components/form-control/script.js

That review makes it possible the custom-select polyfill to work inside the form control component and it is a part of the forms polyfill task.

Forms polyfill

---

docs/README.md
docs/layouts/partials/footer/script-footer.html

* Fixes wrong paths when deploying documentation

Switched RelPermalink to Permalink in production env

---

.gitignore
docs/config/_default/config.toml
docs/layouts/partials/footer/script-footer.html

Fix documentation links

---

docs/README.md
docs/layouts/partials/head/resource-hints.html

Update readme and fix broken font links

---

docs/assets/js/cookieconsent-init.js
docs/assets/js/darkmode.js
docs/config/_default/config.toml
docs/config/_default/params.toml
docs/content/privacy-policy.md
docs/layouts/_default/baseof.html
docs/layouts/partials/footer/script-footer.html
docs/layouts/partials/head/stylesheet.html
docs/package.json

GTM tag and GA live search Custom Event code transfered from https://github.com/CoherentLabs/GameUIComponents/pull/85

Add GA and Cookie Consent plugin/policy

---

.eslintrc.json
components/form-control/errorMessages.js
components/form-control/script.js
components/radial-menu/demo/items-mocking.js
components/rangeslider/orientationUnitsNames.js
components/router/router.js
components/slider/orientationUnitsNames.js
components/text-field/script.js
demo.js
scripts/build.js
scripts/copyright-notice.js
tools/cli/commands/build.js

Add rule for no-sparse-arrays and modify dangling comma

---

interaction-manager/demo/Zoom/pan-zoom.html
interaction-manager/src/interaction-manager.js
interaction-manager/src/lib_components/zoom.js
interaction-manager/src/zoom.js

Add pan and zoom

---

docs/assets/scss/common/_dark.scss
docs/assets/scss/layouts/_sidebar.scss

https://coherent-labs.atlassian.net/browse/COH-16682
This is fix for the following problems 
* https://docs.google.com/spreadsheets/d/1Un1kyMCgvmtB_x_zdvUXnXJtrUfY_bObHCmoxdNY3Ac/edit?pli=1#gid=0&range=A10
https://lh3.googleusercontent.com/epYmk64NQ3vx8wSP_-vhoaYoZb0wMyt4O8J4x5BK3UQlxTOqg4cZy4Er6a5RD1uycJSNlP_FrFeyyjyLyv9FPtd1tjHCz9e9sZnyNIcOeaMswjSL-Tjz-5LFQ4N7WeISgfsEQBKgHqdaQMH2egppvMpImNqlrNQHH0j80hVtgoSEAFZhwkNmbQj3yg
* https://docs.google.com/spreadsheets/d/1Un1kyMCgvmtB_x_zdvUXnXJtrUfY_bObHCmoxdNY3Ac/edit?pli=1#gid=0&range=A11
https://lh4.googleusercontent.com/dX7ERXqcjXFbh96mLCZlF52iPO4TX_7-gDe8YbwsIhEpA_Kl6Fy4lRudtnht0OhVByu7FHUTKOTIE5UmFG0zRO2dJDYllwEIsBWxjcWAkR3yhPqVNJtFFh2UddNcDjTR5yWjM4moQFUiQjtdNpwnyCAJA0VhUYXOuy-YwL0IHpoIYAx_wuqveKHMeQ
* Also fixed scrollbar on when …

Fixed scrollbar styles

---

components/checkbox/package.json
components/checkbox/script.js

Add checked attribute to checkbox

---

components/checkbox/package.json
components/checkbox/script.js

Add setter for the checked attribute

---

docs/config/_default/languages.toml

To test you'll need to checkout the temp branch with the correct file structure setup. There's no need to update the folders at this point as we don't have Korean translations yet - so we're keeping the directories as they are to avoid loosing file change history (at least for now).
Added the languages config file. For some reason it won' work if it is in the doks file, it needs to be in the current repo.
The temp branch is [this one](https://github.com/CoherentLabs/GameUIComponents/tree/temp/multiple-languages-dirs). You'll need to check it out and test the multilingual support there. Keep in mind that only the home and the accordion component pages are translated.

Configure multiple languages

---

components/slider/package.json
components/slider/script.js

Move attribute access to connectedCallback

---

components/dropdown/package.json
components/scrollable-container/package.json
components/tooltip/package.json
components/tooltip/script.js

Fixed issue with changing position on second tooltip activation

---

.github/dependabot.yml
.github/workflows/node.js.yml
tools/cli/package-lock.json
tools/cli/tests/start-demo.test.js
tools/cli/tests/test-helpers/expected.js

Add continuous integration action for Dependabot PRs Update package-lock files

Add continuous integration action for Dependabot PRs

---

.eslintignore
.github/workflows/node.js.yml
package-lock.json
package.json
tools/tests/accordion-menu/test.js
tools/tests/actions.js
tools/tests/automatic-grid/test.js
tools/tests/checkbox/test.js
tools/tests/comprehensive-components-test/templates.js
tools/tests/comprehensive-components-test/test.js
tools/tests/define-engine.js
tools/tests/karma.conf.js
tools/tests/menu/test.js
tools/tests/modal/test.js
tools/tests/progress-bar/test.js
tools/tests/radial-menu/test.js
tools/tests/radio-button/test.js
tools/tests/rangeslider/test.js
tools/tests/scrollable-container/test.js
tools/tests/switch/test.js
tools/tests/tabs/test.js
tools/tests/text-field/test.js
tools/tests/tooltip/test.js

* A test that includes all components in one page
* Added basic `data-bind-for` test - a check to isolate these tests to run only in Cohtml and the `data-bind-for` test included as I have spend my time for the task for more tests.
Not relevant to PR: I have also started to create a test for the User Interface but it requires another karma config / page setup to run it and bigger changes are needed to the testing evironment so I decided to stop at some point.

Additional Component Tests

---

components/rangeslider/orientationUnitsNames.js
components/rangeslider/package.json
components/rangeslider/script.js

Remove rangeslider rect caching

---

README.md
components/checkbox/script.js
docs/content/en/_index.md
tools/cli/README.md
tools/cli/package-lock.json
tools/cli/package.json
tools/cli/templates/script.template.js
tools/cli/tests/test-helpers/expected.js

Updated the components' readme to reflect the new way of creating a component using the isConnected check.
Updated the CLI docs and version(the automation will publish it automatically).
Fixed incorrect code template in the CLI.

Update components and CLI docs

---

tools/tests/actions.js
tools/tests/form-control/spec/validation.test.js
tools/tests/form-control/spec/xhr.test.js
tools/tests/form-control/utils/actions.js
tools/tests/package.json

Task + Test Plan: https://coherent-labs.atlassian.net/browse/COH-17791
* Added waiting to set textContent on element for loadend form event
* Added util function for retrying a function call to pass
* Fixed xhr test by delaying the assert with 200 frames and fixed hang

Fixed flaky validation form and xhr tests

---

scripts/publish-gh-pages.js

[Task](https://coherent-labs.atlassian.net/browse/COH-17857)
Doks repo PR -> https://github.com/CoherentLabs/doks/pull/23

Updated doks theme ref and removed the second build of the documentation

---

tools/tests/form-control/utils/actions.js

[Task & test plan (description of the problem)](https://coherent-labs.atlassian.net/browse/COH-17914)

Clear loadend event after it has been handeled

---

tools/cli/package.json

Update CLI version

---

docs/content/en/interaction-manager/dropzone.md
interaction-manager/package.json
interaction-manager/src/lib_components/dropzone.js

Add drop event and preventdefault to dropzone

---

components/rangeslider/README.md
components/rangeslider/demo/demo.html
components/rangeslider/script.js
tools/tests/comprehensive-components-test/templates.js

Fixed rangeslider min-max value calculations

---

tools/cli/commands/project/create.js
tools/cli/package.json
tools/cli/templates/projects/vite/index.js
tools/cli/templates/projects/vite/package.json
tools/cli/templates/projects/webpack/index.js
tools/cli/templates/projects/webpack/package.json

https://coherent-labs.atlassian.net/browse/COH-18088

Update CLI templates to use latest components

---

tools/cli/package.json
tools/cli/templates/component/package.template.json
tools/cli/tests/test-helpers/expected.js

Add html-loader to component package.json

---

.github/workflows/node.js.yml
README.md
docs/config/_default/menu.toml

[Task](https://coherent-labs.atlassian.net/browse/COH-18073)
You can test the badge status here -> https://github.com/alien1976/GameUIComponents

Trigger run tests action on push to master. Changed badge link to the correct one

---

tools/cli/templates/component/script.template.js
tools/cli/tests/test-helpers/expected.js

Update component template to match the latest version of the components

---

components/radio-button/demo/demo.html
components/radio-button/package.json
components/radio-button/script.js
components/radio-button/style.css
tools/tests/radio-button/test.js

[Task](https://coherent-labs.atlassian.net/browse/COH-18179)

Added dynamic attributes of the radio button component

---

.github/release.yml
.github/workflows/publish.yml
README.md
docs/config/_default/menu.toml
docs/layouts/partials/sidebar/auto-collapsible-menu.html
package-lock.json
package.json
scripts/publish.js

Added readme describing how the workflow works. Updated scripts for tagging packages, generating release notes, and making release to github. Added changelog link to the documentation
[Task](https://coherent-labs.atlassian.net/browse/COH-18389)
Please read the readme about how the workflow works and leave any comments here if it is not clear or you don't like some part of the workflow so we can improve it.

Added workflow for releasing new versions

---

components/carousel/demo.js
components/carousel/demo/demo.js
components/carousel/index.html
components/carousel/package.json

Use correct file structure for carousel

---

components/carousel/demo.js
components/carousel/package.json
components/checkbox/demo.js
components/checkbox/package.json
components/modal/demo.js
components/modal/package.json
components/tabs/demo.js
components/tabs/package.json

Add polyfills to all the component demos

---

tools/tests/scrollable-container/test.js

Disable flaky scrollable container test

---

components/carousel/README.md
components/carousel/package.json
components/carousel/script.js
docs/content/en/components/carousel.md

------------
I have added a function that just checks and show the arrows and rebuilds the pagination and have documented how to use it + have added documentation on how to programmatically navigate.
This PR encompasses these two tasks:
[COH-18834](https://coherent-labs.atlassian.net/browse/COH-18834)
[COH-18835](https://coherent-labs.atlassian.net/browse/COH-18835)
[COH-18834]: https://coherent-labs.atlassian.net/browse/COH-18834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[COH-18835]: https://coherent-labs.atlassian.net/browse/COH-18835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add rerender function and document usage

---

docs/content/en/command-line-interface/cli.md
tools/cli/README.md
tools/cli/commands/create.js
tools/cli/package.json
tools/cli/tests/test-helpers/utils.js

[Task and test plan.](https://coherent-labs.atlassian.net/browse/COH-18920)

CLI - validate component names

---

components/tabs/index.html
components/tabs/package.json
components/tabs/script.js
components/tabs/style.css
components/tabs/template.html
tools/tests/tabs/test.js

Added support for nested tabs

---

components/scrollable-container/README.md
components/tabs/package.json
components/tabs/script.js
docs/content/en/components/scrollable-container.md
tools/tests/tabs/test.js

[Task](https://coherent-labs.atlassian.net/browse/COH-19122)

Fixed tab panel that is not rendering scrollable container

---

components/slider/package.json
components/slider/script.js
components/stepper/package.json

Change rect height to offsetHeight for the slider

---

components/scrollable-container/package.json

Merging this PR will publish a new version of the scrollable container so the slider fixes about a transformed container take effect.

Scrollable container now works when the container is transformed

---

components/scrollable-container/index.html
components/scrollable-container/style.css

[Task](https://coherent-labs.atlassian.net/browse/COH-18458)

Scrollable container height can be changed via CSS setting it to the component directly

---

components/carousel/README.md
components/carousel/package.json
components/carousel/script.js
tools/tests/carousel/test.js

[Task](https://coherent-labs.atlassian.net/browse/COH-19142)

Carousel now adds 'carousel-current-item' class to the active element

---

components/checkbox/README.md
components/dropdown/README.md
components/form-control/README.md
components/radio-button/README.md
components/scrollable-container/README.md
docs/content/en/components/checkbox.md
docs/content/en/components/dropdown.md
docs/content/en/components/form-control.md
docs/content/en/components/radio-button.md
docs/content/en/components/scrollable-container.md

[This is the list](https://docs.google.com/spreadsheets/d/15pahuzjuxOO2S7DDAthmNANdiF70jZh19v0tHUsxJGo/edit?usp=sharing) of all updated docs.

Update readme files with docs regarding attributes

---

components/carousel/package.json
components/carousel/script.js

Add isRendered to Carousel

---

docs/package.json

https://coherent-labs.atlassian.net/browse/COH-19522

[Internal] Fixed and updated cookie consent in the documentation to the latest version

---

interaction-manager/package.json
interaction-manager/src/lib_components/touch-gestures.js

Fix tap bug

---

tools/cli/package.json
tools/cli/templates/projects/vite/package.json
tools/cli/templates/projects/vite/vite.config.js

[COH-19609] Add html-import to the vite config in the template

---

components/stepper/package.json
components/stepper/script.js
components/stepper/style.css

[COH-19625] Append children so there are no missing nodes

---

components/tooltip/package.json
components/tooltip/script.js

[COH-19667]Set targetElement if none is set in the init

---

scripts/publish-gh-pages.js

[COH-19628] Add force to checkout

---

docs/content/en/interaction-manager/spatial-navigation.md
interaction-manager/package.json
interaction-manager/src/lib_components/spatial-navigation.js
tools/tests/actions.js
tools/tests/interaction-manager/keyboard/test.js
tools/tests/interaction-manager/resize/test.js
tools/tests/interaction-manager/spatial-navigation/test.js
tools/tests/interaction-manager/zoom/test.js

Im spatial navigation custom keybindings

---

components/toast/index.js
components/toast/package.json

https://coherent-labs.atlassian.net/browse/COH-19873

Fixed paths in the index.js of the toast so import works properly

---

docs/content/en/interaction-manager/gamepad.md
interaction-manager/package.json
interaction-manager/src/lib_components/gamepad.js
interaction-manager/src/utils/global-object.js

[COH-19276] [Feature] IM gamepad enchancement

---

components/radial-menu/package.json
components/radial-menu/script.js
tools/tests/radial-menu/items-mocking.js
tools/tests/radial-menu/test.js

[COH-16110] Fix Radial menu is not clearing old items when they are changed

---

interaction-manager/package.json
interaction-manager/src/lib_components/spatial-navigation.js
tools/tests/actions.js
tools/tests/interaction-manager/spatial-navigation/test.js

[COH-18157] Enhancement/keep spatial navigation focus
